[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py *_tests.py
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore:The 'mode.copy_on_write' option is deprecated:FutureWarning
    ignore:The 'mode.copy_on_write' option is deprecated:Warning