# Generated by Django 6.1 on 2026-08-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=250, verbose_name='آیدی چت تلگرام')),
                ('symbol', models.CharField(max_length=20, verbose_name='نماد معاملاتی')),
                ('target_price', models.FloatField(verbose_name='قیمت هدف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
        ),
    ]
