# Generated by Django 6.1 on 2026-09-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, verbose_name='آیدی چت تلگرام')),
                ('symbol', models.CharField(max_length=20, verbose_name='نماد معاملاتی')),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4, verbose_name='نوع پوزیشن')),
                ('entry_price', models.FloatField(verbose_name='قیمت ورود')),
                ('exit_price', models.FloatField(blank=True, null=True, verbose_name='قیمت خروج')),
                ('stop_loss', models.FloatField(blank=True, null=True, verbose_name='استاپ')),
                ('take_profit', models.FloatField(blank=True, null=True, verbose_name='تارگت')),
                ('risk_reward', models.FloatField(default=0.0, verbose_name='ریسک به ریوارد')),
                ('result', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('PENDING', 'Pending')], default='PENDING', max_length=10, verbose_name='نتیجه')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='مسیر عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
        ),
        migrations.AddField(
            model_name='useralert',
            name='market_type',
            field=models.CharField(choices=[('CRYPTO', 'Crypto'), ('FOREX', 'Forex')], default='CRYPTO', max_length=10, verbose_name='نوع مارکت'),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='chat_id',
            field=models.CharField(max_length=50, verbose_name='آیدی چت تلگرام'),
        ),
    ]
