# Generated by Django 6.1.1 on 2026-09-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_tradejournal_useralert_market_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='نماد معاملاتی')),
                ('time_frame', models.CharField(max_length=4, verbose_name='تایم فریم')),
                ('market_type', models.CharField(choices=[('CRYPTO', 'Crypto'), ('FOREX', 'Forex')], default='CRYPTO', max_length=10, verbose_name='نوع مارکت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
        ),
    ]
