# Generated by Django 6.1.1 on 2026-09-23 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, max_length=50, verbose_name='آیدی چت')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tradejournal',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='tradejournal',
            name='risk_reward',
        ),
        migrations.RemoveField(
            model_name='useralert',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='entry_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='قیمت ورود'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='قیمت خروج'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='استاپ'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='تارگت'),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='target_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='قیمت هدف'),
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='bot_app.telegramuser'),
        ),
        migrations.AddField(
            model_name='useralert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bot_app.telegramuser'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='bot_app.telegramuser'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'symbol', 'time_frame', 'market_type')},
        ),
        migrations.AddIndex(
            model_name='tradejournal',
            index=models.Index(fields=['user'], name='bot_app_tra_user_id_2b7941_idx'),
        ),
        migrations.AddIndex(
            model_name='tradejournal',
            index=models.Index(fields=['symbol'], name='bot_app_tra_symbol_38322b_idx'),
        ),
        migrations.AddIndex(
            model_name='useralert',
            index=models.Index(fields=['user', 'is_active'], name='bot_app_use_user_id_7fc1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='useralert',
            index=models.Index(fields=['symbol'], name='bot_app_use_symbol_d276c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='useralert',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'symbol', 'target_price', 'market_type'), name='unique_active_alert'),
        ),
    ]
