# Generated by Django 6.1.1 on 2026-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_telegramuser_remove_tradejournal_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(db_index=True, verbose_name='آیدی چت'),
        ),
    ]
