# Generated by Django 6.1.1 on 2026-09-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_alter_telegramuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradejournal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='bot_app.telegramuser'),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bot_app.telegramuser'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='bot_app.telegramuser'),
        ),
    ]
