# Generated by Django 6.1.1 on 2026-09-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_alter_tradejournal_user_alter_useralert_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPartialExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BigIntegerField(db_index=True)),
                ('symbol', models.CharField(max_length=20)),
                ('exit_price', models.FloatField()),
                ('ratio', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
