# Generated by Django 6.1.1 on 2026-09-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_pendingpartialexit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingPartialExit',
        ),
    ]
