# Generated by Django 6.1.1 on 2026-09-29 10:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_delete_pendingpartialexit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradejournal',
            options={'ordering': ['-entry_time', '-created_at'], 'verbose_name': 'ژورنال معامله', 'verbose_name_plural': 'ژورنال\u200cهای معاملاتی'},
        ),
        migrations.RemoveIndex(
            model_name='tradejournal',
            name='bot_app_tra_user_id_2b7941_idx',
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='کمیسیون ($)'),
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود به معامله'),
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج از معامله'),
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / قابل محاسبه در گزارش\u200cها'),
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت/علت ورود'),
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='سود/زیان خام ($)'),
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='swap',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='سوآپ ($)'),
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='volume',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=12, verbose_name='حجم (لات/تعداد)'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سیستم'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مسیر عکس چارت'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='result',
            field=models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('BE', 'Break Even'), ('PENDING', 'Pending')], default='PENDING', max_length=10, verbose_name='نتیجه'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='حد ضرر (SL)'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='حد سود (TP)'),
        ),
        migrations.AddIndex(
            model_name='tradejournal',
            index=models.Index(fields=['user', 'entry_time'], name='bot_app_tra_user_id_99dacd_idx'),
        ),
        migrations.AddIndex(
            model_name='tradejournal',
            index=models.Index(fields=['result'], name='bot_app_tra_result_cca250_idx'),
        ),
    ]
