# Generated by Django 6.1.1 on 2026-09-29 11:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0009_alter_tradejournal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=15, verbose_name='بالانس اولیه حساب ($)')),
                ('default_risk_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='درصد ریسک در هر معامله (%)')),
                ('default_leverage', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(125)], verbose_name='اهرم/لوریج پیش\u200cفرض')),
                ('receive_daily_reports', models.BooleanField(default=True, verbose_name='دریافت گزارش\u200cهای روزانه')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات کاربر',
                'verbose_name_plural': 'تنظیمات کاربران',
            },
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'کاربر تلگرام', 'verbose_name_plural': 'کاربران تلگرام'},
        ),
        migrations.AlterModelOptions(
            name='useralert',
            options={'ordering': ['-created_at'], 'verbose_name': 'هشدار قیمت', 'verbose_name_plural': 'هشدارهای قیمت'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'دیده\u200cبان', 'verbose_name_plural': 'دیده\u200cبان\u200cها'},
        ),
        migrations.RemoveIndex(
            model_name='tradejournal',
            name='bot_app_tra_user_id_99dacd_idx',
        ),
        migrations.RemoveIndex(
            model_name='useralert',
            name='bot_app_use_symbol_d276c7_idx',
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='market_type',
            field=models.CharField(choices=[('CRYPTO', 'کریپتوکارنسی'), ('FOREX', 'فارکس')], default='CRYPTO', max_length=10, verbose_name='نوع مارکت'),
        ),
        migrations.AddField(
            model_name='useralert',
            name='is_triggered',
            field=models.BooleanField(default=False, verbose_name='فعال\u200cشده / هشدار داده\u200cشده'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='آیدی چت تلگرام'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='بلاک شده'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مسیر تصویر چارت'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / شامل در محاسبات'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات/استراتژی'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='bot_app.telegramuser', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='market_type',
            field=models.CharField(choices=[('CRYPTO', 'کریپتوکارنسی'), ('FOREX', 'فارکس')], default='CRYPTO', max_length=10, verbose_name='نوع مارکت'),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bot_app.telegramuser', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='market_type',
            field=models.CharField(choices=[('CRYPTO', 'کریپتوکارنسی'), ('FOREX', 'فارکس')], default='CRYPTO', max_length=10, verbose_name='نوع مارکت'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='time_frame',
            field=models.CharField(default='1h', max_length=10, verbose_name='تایم فریم'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='bot_app.telegramuser', verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='tradejournal',
            index=models.Index(fields=['user', 'is_active', 'entry_time'], name='bot_app_tra_user_id_6b2c66_idx'),
        ),
        migrations.AddIndex(
            model_name='useralert',
            index=models.Index(fields=['symbol', 'is_active'], name='bot_app_use_symbol_5f230f_idx'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='bot_app.telegramuser', verbose_name='کاربر'),
        ),
    ]
