# Generated by Django 6.1.1 on 2026-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0010_usersetting_alter_telegramuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradejournal',
            name='image_path',
        ),
        migrations.AddField(
            model_name='tradejournal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trade_charts/%Y/%m/', verbose_name='تصویر چارت'),
        ),
    ]
