# Generated by Django 6.1.1 on 2026-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_remove_tradejournal_image_path_tradejournal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradejournal',
            name='position_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
