# Generated by Django 6.1.1 on 2026-10-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0012_tradejournal_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradejournal',
            name='position_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='شناسه پوزیشن'),
        ),
    ]
